# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Set Git User
        run: |
          git config --global user.name "xquare-admin"
          git config --global user.email "teamxquare@gmail.com"
          git remote set-url origin https://xquare-admin:$GH_TOKEN@github.com/semicolondsm/SemicolonDesign_Frontend.git
        env:
          GH_TOKEN: ${{ secrets.GHP_TOKEN }}

      - name: Build
        run: yarn build:all

      - name: Publish
        run: yarn run release
        env:
		      GIT_AUTHOR_NAME: xquare-admin
		      GIT_AUTHOR_EMAIL: teamxquare@gmail.com
		      GIT_COMMITTER_NAME: xquare-admin
		      GIT_COMMITTER_EMAIL: teamxquare@gmail.com
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
